* Tasks
** DONE Add get_images() and get_cover_image() method to Article model.
   CLOSED: [2014-05-28 Wed 22:24]
   - CLOSING NOTE [2014-05-28 Wed 22:27] \\
     Did not implement functions as designed.  Used managers instead to achieve desired functionality.
*** DONE method will try to filter on Image and CoverImage models and return
    CLOSED: [2014-05-28 Wed 22:27]
    - CLOSING NOTE [2014-05-28 Wed 22:28]
    empty set if cannot be found.
** IN-PROGRESS Complete articles.views
*** DONE Add in tags to ArticleDetailView using get_queryset.
    CLOSED: [2014-05-28 Wed 22:28]
    - CLOSING NOTE [2014-05-28 Wed 22:28]
*** TODO Add pagination to all List views and views that return lists of objects.
*** Update AuthorDetailView to be ListView (model after ArticleListView)
*** Include tags_urls for each article in ArticleListView
*** Implement dictionary lookup template filter.
** IN-PROGRESS Implement Image resizing at the view level
*** DONE Install django-imagekit in virtual environment.
    CLOSED: [2014-05-28 Wed 22:33]
    - CLOSING NOTE [2014-05-28 Wed 22:33] \\
      Thank you for being Python 3 compliant.
*** DONE Install django-imagefit in virtual environment and update requirements.
    CLOSED: [2014-05-29 Thu 22:20]
    - CLOSING NOTE [2014-05-29 Thu 22:20] \\
      Installed django-imagefit version 0.4
*** IN-PROGRESS Use django-imagefit in templates to dynamically create thumbnails.
** Update jetpackjoust settings for django-imagefit thumbnail options
*** Visit django-imagefit docs to see how to update
jetpackjoust/settings/common.py to include thumbnail settings and other
image resizing options e.g. the ones for the boxes etc.











* Site Overview
Below is an overview of the different sections of the website and their
functionality.
